"""empty message

Revision ID: b4934dc6cb60
Revises: b0eb4a8003b6
Create Date: 2024-07-16 10:40:20.850387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils  # type: ignore

# revision identifiers, used by Alembic.
revision: str = 'b4934dc6cb60'
down_revision: Union[str, None] = 'b0eb4a8003b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
